### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cyberphoria** [cyberphoria/Sample-CRUD-Backend#1]
### Phase 3
  - [x] DatabaseCLI
    - [x] Sample Input statements
    - [x] DatabaseCLITest
  - [x] DatabasePresenter
    - [x] DatabasePresenterTest
  - [x] Move classes into packages

### Phase 4
  - [x] Test app from terminal
  - [x] Additional Requirement
    - ~~[ ] Warehouse + Locations (multiple tables + [ASSIGN (ID) (LOCATION_ID)] command)~~
    - [x] OR Delete with commend and undelete #9 
      - [x] Add table deletedItems 
      - [x] Add class DeletedItem (attribute: Deletion Comment)
      - [x] [RESTORE (ID) command]
  - [x] Run the app on Replit (???)

### Phase 5
  - [x] README #23 #24 
    - [x] Design Decisions
    - [x] Tests
    - [x] Entering Commands 
  - [x] UML Diagram 
  - ~~[ ] Adjust method privacy~~
  
### Optimization
  - [x] JavaDocs
  - ~~[ ] Use term "Field" instead of attribute?~~
  - [x] Optimize executeCommand(matcher instead of command, userinput?) #13 
  - [x] Output table: bar separators on same line?
  - [x] Give matcher methods to a separate class? #11 
  
### DatabaseCLI
  - [x] update help with correct formatting
  - [x] add table name to read #7 
  - [x] add command - view list of tables? #12 
  - [x] update, delete: return item deleted/created from database #14 
  - [x] DatabaseCLITest: use valid inputs from inputs.json file (greater extensibility)
